services:
  db:
    image: postgres:16
    container_name: WeatherDatabase
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: weatherDB
    ports:
      - "5432:5432"
    networks:
      - weather-net
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: WeatherAPI
    mem_limit: 256m
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/weatherDB
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - weather-net

networks:
  weather-net:

volumes:
 db_data: